### ISSUE TITLE
Scipy 0.14.0 Import Errors - Upgrade to 0.14.1?

### ISSUE THREAD

**Issue by jwenner** [martinisgroup/servers#185]
It seems like with scipy 0.14.0 we sometimes get import errors. I would propose that we upgrade our lab standard to 0.14.1, which seems to fix these problems.

Particular examples where this upgrade works:
   1. #184 
   2. On my computer under 0.14.0 the following line did not work: `from scipy import optimize`. I was also getting a message along the lines of `cannot import name _fblas`. Upgrading to 0.14.1 fixed this issue. Note that this line did work on Pedram's computer w/ 0.14.0.
